// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GroupIS1024;
//
//    var newsFeed = NewsFeed.FromJson(jsonString);

namespace GroupIS1024
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class NewsFeed
    {
        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("data")]
        public List<Sport> Data { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }
    }

    public partial class Sport
    {
        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("date")]
        public Date Date { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("imageUrl")]
        public Uri ImageUrl { get; set; }

        [JsonProperty("readMoreUrl")]
        public Uri ReadMoreUrl { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public enum Date { The27Nov2022Sunday };

    public partial class Sport
    {
        public static NewsFeed FromJson(string json) => JsonConvert.DeserializeObject<NewsFeed>(json, GroupIS1024.Converter1.Settings);
    }

    public static class Serialize1
    {
        public static string ToJson(this NewsFeed self) => JsonConvert.SerializeObject(self, GroupIS1024.Converter1.Settings);
    }

    internal static class Converter1
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                DateConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class DateConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Date) || t == typeof(Date?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "27 Nov 2022,Sunday")
            {
                return Date.The27Nov2022Sunday;
            }
            throw new Exception("Cannot unmarshal type Date");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Date)untypedValue;
            if (value == Date.The27Nov2022Sunday)
            {
                serializer.Serialize(writer, "27 Nov 2022,Sunday");
                return;
            }
            throw new Exception("Cannot marshal type Date");
        }

        public static readonly DateConverter Singleton = new DateConverter();
    }
}
